Add Form Group Handlers
fedandburk/buform pull request #72
Opened 2024-06-17 08:59 UTC by vladtaraban

# Summary
Added Handlers for FormGroups. It will be responsible to handle native methods of representing items. For example, we can handle Swipe Actions, Clicks and use native methods to change representation of FormItems.

2024-06-18 14:20 UTC, prin53 requested changes
I have refactored group handlers a bit to follow the project style.

Every time I interact with the list on the components screen I have an exception:

> System.ArgumentException: Parameter "parameter" (object) cannot be of type System.Int32, as the command type requires an argument of type System.ValueTuple`2[System.Int32,System.Int32]. (Parameter 'parameter')

Looks like the handler passes some wrong value to the command.

2024-06-18 22:44 UTC, vladtaraban commented
I investigated it, the problem is with MoveCommand which should take (startIndex, newIndex), but when we try to call CanExecute we pass just the item we are moving. I didn't change that logic and I am not sure how it worked before. I tried to test it on develop branch and It doesn't work also. I think we can change logic of CanMoveItem to just check if MoveCommand is not null and if needed we can override it in some cases.

2024-06-19 11:51 UTC, vladtaraban commented
@prin53 , You can merge this PR.

2024-06-19 11:55 UTC, prin53 approved these changes

2024-06-19 11:55 UTC, merged